/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ClassLabel from './ClassLabel';





/**
* The ClassLabelList model module.
* @module model/ClassLabelList
* @version 2.0.3
*/
export default class ClassLabelList extends Array {
    /**
    * Constructs a new <code>ClassLabelList</code>.
    * A list of possible class labels.
    * @alias module:model/ClassLabelList
    * @class
    * @extends Array
    */

    constructor() {
        
        super();
        

        
        

        

        return this;
    }

    /**
    * Constructs a <code>ClassLabelList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ClassLabelList} obj Optional instance to populate.
    * @return {module:model/ClassLabelList} The populated <code>ClassLabelList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClassLabelList();

            ApiClient.constructFromObject(data, obj, 'ClassLabel');

            
            

        }
        return obj;
    }









}


