/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.CreateDetails = factory(root.FeersumNluApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreateDetails model module.
   * @module model/CreateDetails
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>CreateDetails</code>.
   * The details of the model instance to create.
   * @alias module:model/CreateDetails
   * @class
   * @param loadFromStore {Boolean} Indicates if a pre-existing model with the specified name should be loaded from the model store. Usually set to False in which case a new model is created with details as specified.
   * @param name {String} The sluggy-url-friendly-name of the instance.
   */
  var exports = function(loadFromStore, name) {
    var _this = this;



    _this['load_from_store'] = loadFromStore;
    _this['name'] = name;
  };

  /**
   * Constructs a <code>CreateDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateDetails} obj Optional instance to populate.
   * @return {module:model/CreateDetails} The populated <code>CreateDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('desc')) {
        obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
      }
      if (data.hasOwnProperty('input_file')) {
        obj['input_file'] = ApiClient.convertToType(data['input_file'], 'String');
      }
      if (data.hasOwnProperty('load_from_store')) {
        obj['load_from_store'] = ApiClient.convertToType(data['load_from_store'], 'Boolean');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * The longer existential description of this instance's purpose in life.
   * @member {String} desc
   */
  exports.prototype['desc'] = undefined;
  /**
   * The input file/model on the server (if any) to use.
   * @member {String} input_file
   */
  exports.prototype['input_file'] = undefined;
  /**
   * Indicates if a pre-existing model with the specified name should be loaded from the model store. Usually set to False in which case a new model is created with details as specified.
   * @member {Boolean} load_from_store
   */
  exports.prototype['load_from_store'] = undefined;
  /**
   * The sluggy-url-friendly-name of the instance.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;



  return exports;
}));


