/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DashboardModelDetail from './DashboardModelDetail';





/**
* The DashboardDetail model module.
* @module model/DashboardDetail
* @version 2.0.3
*/
export default class DashboardDetail {
    /**
    * Constructs a new <code>DashboardDetail</code>.
    * Your dashboard content.
    * @alias module:model/DashboardDetail
    * @class
    * @param apiVersion {String} The version of the http api.
    * @param serviceName {String} The details of this service.
    * @param peakApiHitRate {Number} The peak api hit rate (hits/s) over the last couple of window periods. A window period is in the order of 5 minutes.
    * @param modelList {Array.<module:model/DashboardModelDetail>} A list of models' instance details.
    */

    constructor(apiVersion, serviceName, peakApiHitRate, modelList) {
        

        
        

        this['api_version'] = apiVersion;this['service_name'] = serviceName;this['peak_api_hit_rate'] = peakApiHitRate;this['model_list'] = modelList;

        
    }

    /**
    * Constructs a <code>DashboardDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DashboardDetail} obj Optional instance to populate.
    * @return {module:model/DashboardDetail} The populated <code>DashboardDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardDetail();

            
            
            

            if (data.hasOwnProperty('api_version')) {
                obj['api_version'] = ApiClient.convertToType(data['api_version'], 'String');
            }
            if (data.hasOwnProperty('service_name')) {
                obj['service_name'] = ApiClient.convertToType(data['service_name'], 'String');
            }
            if (data.hasOwnProperty('peak_api_hit_rate')) {
                obj['peak_api_hit_rate'] = ApiClient.convertToType(data['peak_api_hit_rate'], 'Number');
            }
            if (data.hasOwnProperty('model_list')) {
                obj['model_list'] = ApiClient.convertToType(data['model_list'], [DashboardModelDetail]);
            }
        }
        return obj;
    }

    /**
    * The version of the http api.
    * @member {String} api_version
    */
    api_version = undefined;
    /**
    * The details of this service.
    * @member {String} service_name
    */
    service_name = undefined;
    /**
    * The peak api hit rate (hits/s) over the last couple of window periods. A window period is in the order of 5 minutes.
    * @member {Number} peak_api_hit_rate
    */
    peak_api_hit_rate = undefined;
    /**
    * A list of models' instance details.
    * @member {Array.<module:model/DashboardModelDetail>} model_list
    */
    model_list = undefined;








}


