/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.DashboardModelDetail = factory(root.FeersumNluApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DashboardModelDetail model module.
   * @module model/DashboardModelDetail
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>DashboardModelDetail</code>.
   * The model instance detail.
   * @alias module:model/DashboardModelDetail
   * @class
   * @param modelType {String} The type of this model.
   * @param name {String} The sluggy-url-friendly-name of the instance.
   */
  var exports = function(modelType, name) {
    var _this = this;


    _this['model_type'] = modelType;
    _this['name'] = name;

  };

  /**
   * Constructs a <code>DashboardModelDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DashboardModelDetail} obj Optional instance to populate.
   * @return {module:model/DashboardModelDetail} The populated <code>DashboardModelDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('desc')) {
        obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
      }
      if (data.hasOwnProperty('model_type')) {
        obj['model_type'] = ApiClient.convertToType(data['model_type'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('peak_api_hit_rate')) {
        obj['peak_api_hit_rate'] = ApiClient.convertToType(data['peak_api_hit_rate'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The longer existential description of this instance's purpose in life.
   * @member {String} desc
   */
  exports.prototype['desc'] = undefined;
  /**
   * The type of this model.
   * @member {String} model_type
   */
  exports.prototype['model_type'] = undefined;
  /**
   * The sluggy-url-friendly-name of the instance.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The peak api hit rate (hits/s) over the last couple of window periods. A window period is in the order of 5 minutes.
   * @member {Number} peak_api_hit_rate
   */
  exports.prototype['peak_api_hit_rate'] = undefined;



  return exports;
}));


