/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DucklingInstanceDetail model module.
* @module model/DucklingInstanceDetail
* @version 2.0.3
*/
export default class DucklingInstanceDetail {
    /**
    * Constructs a new <code>DucklingInstanceDetail</code>.
    * The model instance detail.
    * @alias module:model/DucklingInstanceDetail
    * @class
    * @param id {String} The unique id of a specific version of the model instance.
    * @param name {String} The sluggy-url-friendly-name of the instance.
    */

    constructor(id, name) {
        

        
        

        this['id'] = id;this['name'] = name;

        
    }

    /**
    * Constructs a <code>DucklingInstanceDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DucklingInstanceDetail} obj Optional instance to populate.
    * @return {module:model/DucklingInstanceDetail} The populated <code>DucklingInstanceDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DucklingInstanceDetail();

            
            
            

            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * The longer existential description of this instance's purpose in life.
    * @member {String} desc
    */
    desc = undefined;
    /**
    * The unique id of a specific version of the model instance.
    * @member {String} id
    */
    id = undefined;
    /**
    * The sluggy-url-friendly-name of the instance.
    * @member {String} name
    */
    name = undefined;








}


