/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Entity model module.
* @module model/Entity
* @version 2.0.3
*/
export default class Entity {
    /**
    * Constructs a new <code>Entity</code>.
    * An entity.
    * @alias module:model/Entity
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Entity</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Entity} obj Optional instance to populate.
    * @return {module:model/Entity} The populated <code>Entity</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Entity();

            
            
            

        }
        return obj;
    }









}


