/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The LabelledTextSample model module.
* @module model/LabelledTextSample
* @version 2.0.3
*/
export default class LabelledTextSample {
    /**
    * Constructs a new <code>LabelledTextSample</code>.
    * Labelled text sample.
    * @alias module:model/LabelledTextSample
    * @class
    * @param text {String} 
    * @param label {String} 
    */

    constructor(text, label) {
        

        
        

        this['text'] = text;this['label'] = label;

        
    }

    /**
    * Constructs a <code>LabelledTextSample</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LabelledTextSample} obj Optional instance to populate.
    * @return {module:model/LabelledTextSample} The populated <code>LabelledTextSample</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LabelledTextSample();

            
            
            

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} text
    */
    text = undefined;
    /**
    * @member {String} label
    */
    label = undefined;








}


