/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LabelledTextSample'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LabelledTextSample'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.LabelledTextSampleList = factory(root.FeersumNluApi.ApiClient, root.FeersumNluApi.LabelledTextSample);
  }
}(this, function(ApiClient, LabelledTextSample) {
  'use strict';




  /**
   * The LabelledTextSampleList model module.
   * @module model/LabelledTextSampleList
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>LabelledTextSampleList</code>.
   * List of labelled text samples.
   * @alias module:model/LabelledTextSampleList
   * @class
   * @extends Array
   */
  var exports = function() {
    var _this = this;
    _this = new Array();
    Object.setPrototypeOf(_this, exports);

    return _this;
  };

  /**
   * Constructs a <code>LabelledTextSampleList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabelledTextSampleList} obj Optional instance to populate.
   * @return {module:model/LabelledTextSampleList} The populated <code>LabelledTextSampleList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'LabelledTextSample');

    }
    return obj;
  }




  return exports;
}));


