/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.LabeledWordManifold = factory(root.FeersumNluApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LabeledWordManifold model module.
   * @module model/LabeledWordManifold
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>LabeledWordManifold</code>.
   * A labelled (e.g. lang_code labelled) word manifold instance.
   * @alias module:model/LabeledWordManifold
   * @class
   * @param label {String} The language code label.
   * @param wordManifold {String} The name of the word manifold to use for the language code.
   */
  var exports = function(label, wordManifold) {
    var _this = this;

    _this['label'] = label;
    _this['word_manifold'] = wordManifold;
  };

  /**
   * Constructs a <code>LabeledWordManifold</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LabeledWordManifold} obj Optional instance to populate.
   * @return {module:model/LabeledWordManifold} The populated <code>LabeledWordManifold</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('word_manifold')) {
        obj['word_manifold'] = ApiClient.convertToType(data['word_manifold'], 'String');
      }
    }
    return obj;
  }

  /**
   * The language code label.
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * The name of the word manifold to use for the language code.
   * @member {String} word_manifold
   */
  exports.prototype['word_manifold'] = undefined;



  return exports;
}));


