/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Lr4InstanceDetail model module.
* @module model/Lr4InstanceDetail
* @version 2.0.3
*/
export default class Lr4InstanceDetail {
    /**
    * Constructs a new <code>Lr4InstanceDetail</code>.
    * The model instance detail.
    * @alias module:model/Lr4InstanceDetail
    * @class
    * @param name {String} The sluggy-url-friendly-name of the instance.
    * @param id {String} The unique id of a specific version of the model instance.
    * @param modelFile {String} The pre-trained model this instance was created from.
    */

    constructor(name, id, modelFile) {
        

        
        

        this['name'] = name;this['id'] = id;this['model_file'] = modelFile;

        
    }

    /**
    * Constructs a <code>Lr4InstanceDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Lr4InstanceDetail} obj Optional instance to populate.
    * @return {module:model/Lr4InstanceDetail} The populated <code>Lr4InstanceDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Lr4InstanceDetail();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('desc')) {
                obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
            }
            if (data.hasOwnProperty('model_file')) {
                obj['model_file'] = ApiClient.convertToType(data['model_file'], 'String');
            }
        }
        return obj;
    }

    /**
    * The sluggy-url-friendly-name of the instance.
    * @member {String} name
    */
    name = undefined;
    /**
    * The unique id of a specific version of the model instance.
    * @member {String} id
    */
    id = undefined;
    /**
    * The longer existential description of this instance's purpose in life.
    * @member {String} desc
    */
    desc = undefined;
    /**
    * The pre-trained model this instance was created from.
    * @member {String} model_file
    */
    model_file = undefined;








}


