/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Lr4InstanceDetail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Lr4InstanceDetail'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.Lr4InstanceDetailList = factory(root.FeersumNluApi.ApiClient, root.FeersumNluApi.Lr4InstanceDetail);
  }
}(this, function(ApiClient, Lr4InstanceDetail) {
  'use strict';




  /**
   * The Lr4InstanceDetailList model module.
   * @module model/Lr4InstanceDetailList
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>Lr4InstanceDetailList</code>.
   * A list of models&#39; instance details.
   * @alias module:model/Lr4InstanceDetailList
   * @class
   * @extends Array
   */
  var exports = function() {
    var _this = this;
    _this = new Array();
    Object.setPrototypeOf(_this, exports);

    return _this;
  };

  /**
   * Constructs a <code>Lr4InstanceDetailList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Lr4InstanceDetailList} obj Optional instance to populate.
   * @return {module:model/Lr4InstanceDetailList} The populated <code>Lr4InstanceDetailList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'Lr4InstanceDetail');

    }
    return obj;
  }




  return exports;
}));


