/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.ModelDate = factory(root.FeersumNluApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModelDate model module.
   * @module model/ModelDate
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>ModelDate</code>.
   * A structured date-time string with a best guess on the specificity/granularity (i.e. hour, day, month)
   * @alias module:model/ModelDate
   * @class
   * @param _date {String} 
   * @param granularity {module:model/ModelDate.GranularityEnum} 
   */
  var exports = function(_date, granularity) {
    var _this = this;

    _this['date'] = _date;
    _this['granularity'] = granularity;
  };

  /**
   * Constructs a <code>ModelDate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelDate} obj Optional instance to populate.
   * @return {module:model/ModelDate} The populated <code>ModelDate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
      if (data.hasOwnProperty('granularity')) {
        obj['granularity'] = ApiClient.convertToType(data['granularity'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {module:model/ModelDate.GranularityEnum} granularity
   */
  exports.prototype['granularity'] = undefined;


  /**
   * Allowed values for the <code>granularity</code> property.
   * @enum {String}
   * @readonly
   */
  exports.GranularityEnum = {
    /**
     * value: "second"
     * @const
     */
    "second": "second",
    /**
     * value: "minute"
     * @const
     */
    "minute": "minute",
    /**
     * value: "hour"
     * @const
     */
    "hour": "hour",
    /**
     * value: "day"
     * @const
     */
    "day": "day",
    /**
     * value: "week"
     * @const
     */
    "week": "week",
    /**
     * value: "month"
     * @const
     */
    "month": "month",
    /**
     * value: "year"
     * @const
     */
    "year": "year"  };


  return exports;
}));


