/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ModelDate model module.
* @module model/ModelDate
* @version 2.0.3
*/
export default class ModelDate {
    /**
    * Constructs a new <code>ModelDate</code>.
    * A structured date-time string with a best guess on the specificity/granularity (i.e. hour, day, month)
    * @alias module:model/ModelDate
    * @class
    * @param _date {String} 
    * @param granularity {module:model/ModelDate.GranularityEnum} 
    */

    constructor(_date, granularity) {
        

        
        

        this['date'] = _date;this['granularity'] = granularity;

        
    }

    /**
    * Constructs a <code>ModelDate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelDate} obj Optional instance to populate.
    * @return {module:model/ModelDate} The populated <code>ModelDate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelDate();

            
            
            

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('granularity')) {
                obj['granularity'] = ApiClient.convertToType(data['granularity'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} date
    */
    date = undefined;
    /**
    * @member {module:model/ModelDate.GranularityEnum} granularity
    */
    granularity = undefined;






    /**
    * Allowed values for the <code>granularity</code> property.
    * @enum {String}
    * @readonly
    */
    static GranularityEnum = {
    
        /**
         * value: "second"
         * @const
         */
        "second": "second",
    
        /**
         * value: "minute"
         * @const
         */
        "minute": "minute",
    
        /**
         * value: "hour"
         * @const
         */
        "hour": "hour",
    
        /**
         * value: "day"
         * @const
         */
        "day": "day",
    
        /**
         * value: "week"
         * @const
         */
        "week": "week",
    
        /**
         * value: "month"
         * @const
         */
        "month": "month",
    
        /**
         * value: "year"
         * @const
         */
        "year": "year"    
    };



}


