/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ScoredLabel model module.
* @module model/ScoredLabel
* @version 2.0.3
*/
export default class ScoredLabel {
    /**
    * Constructs a new <code>ScoredLabel</code>.
    * A class label with an associated probablity.
    * @alias module:model/ScoredLabel
    * @class
    * @param label {String} 
    * @param probability {Number} 
    */

    constructor(label, probability) {
        

        
        

        this['label'] = label;this['probability'] = probability;

        
    }

    /**
    * Constructs a <code>ScoredLabel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ScoredLabel} obj Optional instance to populate.
    * @return {module:model/ScoredLabel} The populated <code>ScoredLabel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScoredLabel();

            
            
            

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('probability')) {
                obj['probability'] = ApiClient.convertToType(data['probability'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} label
    */
    label = undefined;
    /**
    * @member {Number} probability
    */
    probability = undefined;








}


