/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.SimilarityInstanceDetail = factory(root.FeersumNluApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SimilarityInstanceDetail model module.
   * @module model/SimilarityInstanceDetail
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>SimilarityInstanceDetail</code>.
   * The model instance detail.
   * @alias module:model/SimilarityInstanceDetail
   * @class
   * @param name {String} The sluggy-url-friendly-name of the instance.
   * @param id {String} The unique id of a specific version of the model instance.
   * @param similarWords {Array.<String>} The list of similar words to test against.
   * @param threshold {Number} The threshold below which words are not similar.
   * @param wordManifold {String} The word manifold used to measure word similarity.
   */
  var exports = function(name, id, similarWords, threshold, wordManifold) {
    var _this = this;

    _this['name'] = name;
    _this['id'] = id;

    _this['similar_words'] = similarWords;
    _this['threshold'] = threshold;
    _this['word_manifold'] = wordManifold;
  };

  /**
   * Constructs a <code>SimilarityInstanceDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimilarityInstanceDetail} obj Optional instance to populate.
   * @return {module:model/SimilarityInstanceDetail} The populated <code>SimilarityInstanceDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('desc')) {
        obj['desc'] = ApiClient.convertToType(data['desc'], 'String');
      }
      if (data.hasOwnProperty('similar_words')) {
        obj['similar_words'] = ApiClient.convertToType(data['similar_words'], ['String']);
      }
      if (data.hasOwnProperty('threshold')) {
        obj['threshold'] = ApiClient.convertToType(data['threshold'], 'Number');
      }
      if (data.hasOwnProperty('word_manifold')) {
        obj['word_manifold'] = ApiClient.convertToType(data['word_manifold'], 'String');
      }
    }
    return obj;
  }

  /**
   * The sluggy-url-friendly-name of the instance.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The unique id of a specific version of the model instance.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The longer existential description of this instance's purpose in life.
   * @member {String} desc
   */
  exports.prototype['desc'] = undefined;
  /**
   * The list of similar words to test against.
   * @member {Array.<String>} similar_words
   */
  exports.prototype['similar_words'] = undefined;
  /**
   * The threshold below which words are not similar.
   * @member {Number} threshold
   */
  exports.prototype['threshold'] = undefined;
  /**
   * The word manifold used to measure word similarity.
   * @member {String} word_manifold
   */
  exports.prototype['word_manifold'] = undefined;



  return exports;
}));


