/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TextInput model module.
* @module model/TextInput
* @version 2.0.3
*/
export default class TextInput {
    /**
    * Constructs a new <code>TextInput</code>.
    * The text input to be classified, matched or parsed.
    * @alias module:model/TextInput
    * @class
    * @param text {String} 
    */

    constructor(text) {
        

        
        

        this['text'] = text;

        
    }

    /**
    * Constructs a <code>TextInput</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TextInput} obj Optional instance to populate.
    * @return {module:model/TextInput} The populated <code>TextInput</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextInput();

            
            
            

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} text
    */
    text = undefined;








}


