/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.TotalSamples = factory(root.FeersumNluApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TotalSamples model module.
   * @module model/TotalSamples
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>TotalSamples</code>.
   * The total number of samples of this type now loaded into the model.
   * @alias module:model/TotalSamples
   * @class
   * @param totalSamples {Number} 
   */
  var exports = function(totalSamples) {
    var _this = this;

    _this['total_samples'] = totalSamples;
  };

  /**
   * Constructs a <code>TotalSamples</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TotalSamples} obj Optional instance to populate.
   * @return {module:model/TotalSamples} The populated <code>TotalSamples</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total_samples')) {
        obj['total_samples'] = ApiClient.convertToType(data['total_samples'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} total_samples
   */
  exports.prototype['total_samples'] = undefined;



  return exports;
}));


