/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TotalSamples model module.
* @module model/TotalSamples
* @version 2.0.3
*/
export default class TotalSamples {
    /**
    * Constructs a new <code>TotalSamples</code>.
    * The total number of samples of this type now loaded into the model.
    * @alias module:model/TotalSamples
    * @class
    * @param totalSamples {Number} 
    */

    constructor(totalSamples) {
        

        
        

        this['total_samples'] = totalSamples;

        
    }

    /**
    * Constructs a <code>TotalSamples</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TotalSamples} obj Optional instance to populate.
    * @return {module:model/TotalSamples} The populated <code>TotalSamples</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TotalSamples();

            
            
            

            if (data.hasOwnProperty('total_samples')) {
                obj['total_samples'] = ApiClient.convertToType(data['total_samples'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} total_samples
    */
    total_samples = undefined;








}


