/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LabeledWordManifold'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LabeledWordManifold'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.TrainDetails = factory(root.FeersumNluApi.ApiClient, root.FeersumNluApi.LabeledWordManifold);
  }
}(this, function(ApiClient, LabeledWordManifold) {
  'use strict';




  /**
   * The TrainDetails model module.
   * @module model/TrainDetails
   * @version 2.0.3
   */

  /**
   * Constructs a new <code>TrainDetails</code>.
   * The parameters provided to the train operation.
   * @alias module:model/TrainDetails
   * @class
   * @param immediateMode {Boolean} Causes the API call to be blocking and return only once training is complete. Forced to true in the current implementation.
   */
  var exports = function(immediateMode) {
    var _this = this;

    _this['immediate_mode'] = immediateMode;



  };

  /**
   * Constructs a <code>TrainDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainDetails} obj Optional instance to populate.
   * @return {module:model/TrainDetails} The populated <code>TrainDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('immediate_mode')) {
        obj['immediate_mode'] = ApiClient.convertToType(data['immediate_mode'], 'Boolean');
      }
      if (data.hasOwnProperty('threshold')) {
        obj['threshold'] = ApiClient.convertToType(data['threshold'], 'Number');
      }
      if (data.hasOwnProperty('word_manifold')) {
        obj['word_manifold'] = ApiClient.convertToType(data['word_manifold'], 'String');
      }
      if (data.hasOwnProperty('word_manifold_list')) {
        obj['word_manifold_list'] = ApiClient.convertToType(data['word_manifold_list'], [LabeledWordManifold]);
      }
    }
    return obj;
  }

  /**
   * Causes the API call to be blocking and return only once training is complete. Forced to true in the current implementation.
   * @member {Boolean} immediate_mode
   */
  exports.prototype['immediate_mode'] = undefined;
  /**
   * There is typically some model dependent threshold to be set upon training which is possibly mutable post training. This is that threshold.
   * @member {Number} threshold
   */
  exports.prototype['threshold'] = undefined;
  /**
   * The word manifold instance to use for training and later inference.   Rather use the word_manifold_list for supplying a language labelled list of word manifold instances to use in a multi-language system. 
   * @member {String} word_manifold
   */
  exports.prototype['word_manifold'] = undefined;
  /**
   * The list of labelled word manifolds to use for training.
   * @member {Array.<module:model/LabeledWordManifold>} word_manifold_list
   */
  exports.prototype['word_manifold_list'] = undefined;



  return exports;
}));


