/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WordAndThreshold model module.
* @module model/WordAndThreshold
* @version 2.0.3
*/
export default class WordAndThreshold {
    /**
    * Constructs a new <code>WordAndThreshold</code>.
    * A word and a threshold.
    * @alias module:model/WordAndThreshold
    * @class
    * @param word {String} 
    * @param threshold {Number} 
    */

    constructor(word, threshold) {
        

        
        

        this['word'] = word;this['threshold'] = threshold;

        
    }

    /**
    * Constructs a <code>WordAndThreshold</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WordAndThreshold} obj Optional instance to populate.
    * @return {module:model/WordAndThreshold} The populated <code>WordAndThreshold</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WordAndThreshold();

            
            
            

            if (data.hasOwnProperty('word')) {
                obj['word'] = ApiClient.convertToType(data['word'], 'String');
            }
            if (data.hasOwnProperty('threshold')) {
                obj['threshold'] = ApiClient.convertToType(data['threshold'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} word
    */
    word = undefined;
    /**
    * @member {Number} threshold
    */
    threshold = undefined;








}


