/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WordAndDistance model module.
* @module model/WordAndDistance
* @version 2.0.3
*/
export default class WordAndDistance {
    /**
    * Constructs a new <code>WordAndDistance</code>.
    * A word and a distance.
    * @alias module:model/WordAndDistance
    * @class
    * @param distance {Number} 
    * @param word {String} 
    */

    constructor(distance, word) {
        

        
        

        this['distance'] = distance;this['word'] = word;

        
    }

    /**
    * Constructs a <code>WordAndDistance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WordAndDistance} obj Optional instance to populate.
    * @return {module:model/WordAndDistance} The populated <code>WordAndDistance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WordAndDistance();

            
            
            

            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
            if (data.hasOwnProperty('word')) {
                obj['word'] = ApiClient.convertToType(data['word'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} distance
    */
    distance = undefined;
    /**
    * @member {String} word
    */
    word = undefined;








}


