/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DashboardDetail'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DashboardDetail'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.DashboardApi = factory(root.FeersumNluApi.ApiClient, root.FeersumNluApi.DashboardDetail);
  }
}(this, function(ApiClient, DashboardDetail) {
  'use strict';

  /**
   * Dashboard service.
   * @module api/DashboardApi
   * @version 2.0.3
   */

  /**
   * Constructs a new DashboardApi. 
   * @alias module:api/DashboardApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the controllersDashboardControllerDashboardGetDetails operation.
     * @callback module:api/DashboardApi~controllersDashboardControllerDashboardGetDetailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DashboardDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Your service dashboard.
     * Get your list of loaded model instances, the total API hits for each, API version, etc.
     * @param {module:api/DashboardApi~controllersDashboardControllerDashboardGetDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DashboardDetail}
     */
    this.controllersDashboardControllerDashboardGetDetails = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['APIKeyHeader'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = DashboardDetail;

      return this.apiClient.callApi(
        '/dashboard', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
