/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClassLabelList from '../model/ClassLabelList';
import ClassLabelPair from '../model/ClassLabelPair';
import CreateDetails from '../model/CreateDetails';
import InstanceDetail from '../model/InstanceDetail';
import InstanceDetailList from '../model/InstanceDetailList';
import LabelledTextSampleList from '../model/LabelledTextSampleList';
import ScoredLabelList from '../model/ScoredLabelList';
import TextInput from '../model/TextInput';
import TotalSamples from '../model/TotalSamples';
import TrainDetails from '../model/TrainDetails';

/**
* Intent_classifiers service.
* @module api/Intent_classifiersApi
* @version 2.0.3
*/
export default class Intent_classifiersApi {

    /**
    * Constructs a new Intent_classifiersApi. 
    * @alias module:api/Intent_classifiersApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add training samples.
     * Add training samples to named intent classifier. Returns the classifier&#39;s updated number of training samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/LabelledTextSampleList} labelledTextSampleList List of labelled text samples.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TotalSamples} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierAddTrainingSamplesWithHttpInfo(instanceName, labelledTextSampleList) {
      let postBody = labelledTextSampleList;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierAddTrainingSamples");
      }

      // verify the required parameter 'labelledTextSampleList' is set
      if (labelledTextSampleList === undefined || labelledTextSampleList === null) {
        throw new Error("Missing the required parameter 'labelledTextSampleList' when calling controllersIntentClassifiersControllerIntentClassifierAddTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TotalSamples;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/training_samples', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Add training samples.
     * Add training samples to named intent classifier. Returns the classifier&#39;s updated number of training samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/LabelledTextSampleList} labelledTextSampleList List of labelled text samples.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TotalSamples}
     */
    controllersIntentClassifiersControllerIntentClassifierAddTrainingSamples(instanceName, labelledTextSampleList) {
      return this.controllersIntentClassifiersControllerIntentClassifierAddTrainingSamplesWithHttpInfo(instanceName, labelledTextSampleList)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create an intent classifier.
     * Create a new intent classifier or load one from the store. Returns the details of the new or loaded instance.
     * @param {module:model/CreateDetails} createDetails The details of the instance to create.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetail} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierCreateWithHttpInfo(createDetails) {
      let postBody = createDetails;

      // verify the required parameter 'createDetails' is set
      if (createDetails === undefined || createDetails === null) {
        throw new Error("Missing the required parameter 'createDetails' when calling controllersIntentClassifiersControllerIntentClassifierCreate");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetail;

      return this.apiClient.callApi(
        '/intent_classifiers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create an intent classifier.
     * Create a new intent classifier or load one from the store. Returns the details of the new or loaded instance.
     * @param {module:model/CreateDetails} createDetails The details of the instance to create.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetail}
     */
    controllersIntentClassifiersControllerIntentClassifierCreate(createDetails) {
      return this.controllersIntentClassifiersControllerIntentClassifierCreateWithHttpInfo(createDetails)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Endpoint to aid in the curation of a model instance.
     * Returns the list of samples behind a cell of the confusion matrix of the training or testing samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/ClassLabelPair} labelPair The true label, predicted label and matrix (train/test) to use.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LabelledTextSampleList} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierCurateWithHttpInfo(instanceName, labelPair) {
      let postBody = labelPair;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierCurate");
      }

      // verify the required parameter 'labelPair' is set
      if (labelPair === undefined || labelPair === null) {
        throw new Error("Missing the required parameter 'labelPair' when calling controllersIntentClassifiersControllerIntentClassifierCurate");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LabelledTextSampleList;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/curate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Endpoint to aid in the curation of a model instance.
     * Returns the list of samples behind a cell of the confusion matrix of the training or testing samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/ClassLabelPair} labelPair The true label, predicted label and matrix (train/test) to use.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LabelledTextSampleList}
     */
    controllersIntentClassifiersControllerIntentClassifierCurate(instanceName, labelPair) {
      return this.controllersIntentClassifiersControllerIntentClassifierCurateWithHttpInfo(instanceName, labelPair)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete training samples.
     * Delete the training samples of the named intent classifier. Returns the deleted samples.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LabelledTextSampleList} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierDelTrainingSamplesWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierDelTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LabelledTextSampleList;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/training_samples', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete training samples.
     * Delete the training samples of the named intent classifier. Returns the deleted samples.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LabelledTextSampleList}
     */
    controllersIntentClassifiersControllerIntentClassifierDelTrainingSamples(instanceName) {
      return this.controllersIntentClassifiersControllerIntentClassifierDelTrainingSamplesWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get details of named instance.
     * Returns the details of the named intent classifier instance.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetail} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierGetDetailsWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierGetDetails");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetail;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get details of named instance.
     * Returns the details of the named intent classifier instance.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetail}
     */
    controllersIntentClassifiersControllerIntentClassifierGetDetails(instanceName) {
      return this.controllersIntentClassifiersControllerIntentClassifierGetDetailsWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get list of loaded intent classifiers.
     * Returns the list of loaded intent classifiers.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetailList} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierGetDetailsAllWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetailList;

      return this.apiClient.callApi(
        '/intent_classifiers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get list of loaded intent classifiers.
     * Returns the list of loaded intent classifiers.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetailList}
     */
    controllersIntentClassifiersControllerIntentClassifierGetDetailsAll() {
      return this.controllersIntentClassifiersControllerIntentClassifierGetDetailsAllWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get list of possible labels.
     * Returns the classifier&#39;s list of possible class labels.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ClassLabelList} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierGetLabelsWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierGetLabels");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ClassLabelList;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/get_labels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get list of possible labels.
     * Returns the classifier&#39;s list of possible class labels.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ClassLabelList}
     */
    controllersIntentClassifiersControllerIntentClassifierGetLabels(instanceName) {
      return this.controllersIntentClassifiersControllerIntentClassifierGetLabelsWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get training samples.
     * Returns the training samples of the named intent classifier.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LabelledTextSampleList} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierGetTrainingSamplesWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierGetTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LabelledTextSampleList;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/training_samples', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get training samples.
     * Returns the training samples of the named intent classifier.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LabelledTextSampleList}
     */
    controllersIntentClassifiersControllerIntentClassifierGetTrainingSamples(instanceName) {
      return this.controllersIntentClassifiersControllerIntentClassifierGetTrainingSamplesWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Train/update the classifier online with the samples provided.
     * Train/update the classifier online with the samples provided. This operation is more efficient than a full re-train. Returns the classifier&#39;s updated number of training samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/LabelledTextSampleList} labelledTextSampleList List of labelled text samples.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TotalSamples} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierOnlineTrainingSamplesWithHttpInfo(instanceName, labelledTextSampleList) {
      let postBody = labelledTextSampleList;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierOnlineTrainingSamples");
      }

      // verify the required parameter 'labelledTextSampleList' is set
      if (labelledTextSampleList === undefined || labelledTextSampleList === null) {
        throw new Error("Missing the required parameter 'labelledTextSampleList' when calling controllersIntentClassifiersControllerIntentClassifierOnlineTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TotalSamples;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/online_training_samples', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Train/update the classifier online with the samples provided.
     * Train/update the classifier online with the samples provided. This operation is more efficient than a full re-train. Returns the classifier&#39;s updated number of training samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/LabelledTextSampleList} labelledTextSampleList List of labelled text samples.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TotalSamples}
     */
    controllersIntentClassifiersControllerIntentClassifierOnlineTrainingSamples(instanceName, labelledTextSampleList) {
      return this.controllersIntentClassifiersControllerIntentClassifierOnlineTrainingSamplesWithHttpInfo(instanceName, labelledTextSampleList)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Classify intent.
     * Classifies the intent and returns a probability sorted list of classes.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TextInput} textInput The input text.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ScoredLabelList} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierRetrieveWithHttpInfo(instanceName, textInput) {
      let postBody = textInput;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierRetrieve");
      }

      // verify the required parameter 'textInput' is set
      if (textInput === undefined || textInput === null) {
        throw new Error("Missing the required parameter 'textInput' when calling controllersIntentClassifiersControllerIntentClassifierRetrieve");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ScoredLabelList;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/retrieve', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Classify intent.
     * Classifies the intent and returns a probability sorted list of classes.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TextInput} textInput The input text.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ScoredLabelList}
     */
    controllersIntentClassifiersControllerIntentClassifierRetrieve(instanceName, textInput) {
      return this.controllersIntentClassifiersControllerIntentClassifierRetrieveWithHttpInfo(instanceName, textInput)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Train the named intent classifier.
     * Train the named intent classifier with the training and testing data already provided. Returns the updated instance details.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TrainDetails} trainDetails The arguments provided to the train operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetail} and HTTP response
     */
    controllersIntentClassifiersControllerIntentClassifierTrainWithHttpInfo(instanceName, trainDetails) {
      let postBody = trainDetails;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersIntentClassifiersControllerIntentClassifierTrain");
      }

      // verify the required parameter 'trainDetails' is set
      if (trainDetails === undefined || trainDetails === null) {
        throw new Error("Missing the required parameter 'trainDetails' when calling controllersIntentClassifiersControllerIntentClassifierTrain");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetail;

      return this.apiClient.callApi(
        '/intent_classifiers/{instance_name}/train', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Train the named intent classifier.
     * Train the named intent classifier with the training and testing data already provided. Returns the updated instance details.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TrainDetails} trainDetails The arguments provided to the train operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetail}
     */
    controllersIntentClassifiersControllerIntentClassifierTrain(instanceName, trainDetails) {
      return this.controllersIntentClassifiersControllerIntentClassifierTrainWithHttpInfo(instanceName, trainDetails)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
