/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Sentiment', 'model/TextInput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Sentiment'), require('../model/TextInput'));
  } else {
    // Browser globals (root is window)
    if (!root.FeersumNluApi) {
      root.FeersumNluApi = {};
    }
    root.FeersumNluApi.Sentiment_detectorsApi = factory(root.FeersumNluApi.ApiClient, root.FeersumNluApi.Sentiment, root.FeersumNluApi.TextInput);
  }
}(this, function(ApiClient, Sentiment, TextInput) {
  'use strict';

  /**
   * Sentiment_detectors service.
   * @module api/Sentiment_detectorsApi
   * @version 2.0.3
   */

  /**
   * Constructs a new Sentiment_detectorsApi. 
   * @alias module:api/Sentiment_detectorsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the controllersSentimentDetectorsControllerSentimentDetectorRetrieve operation.
     * @callback module:api/Sentiment_detectorsApi~controllersSentimentDetectorsControllerSentimentDetectorRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Sentiment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Detect sentiment.
     * Detect the general sentiment in the input text.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TextInput} textInput The input text.
     * @param {module:api/Sentiment_detectorsApi~controllersSentimentDetectorsControllerSentimentDetectorRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Sentiment}
     */
    this.controllersSentimentDetectorsControllerSentimentDetectorRetrieve = function(instanceName, textInput, callback) {
      var postBody = textInput;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersSentimentDetectorsControllerSentimentDetectorRetrieve");
      }

      // verify the required parameter 'textInput' is set
      if (textInput === undefined || textInput === null) {
        throw new Error("Missing the required parameter 'textInput' when calling controllersSentimentDetectorsControllerSentimentDetectorRetrieve");
      }


      var pathParams = {
        'instance_name': instanceName
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['APIKeyHeader'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Sentiment;

      return this.apiClient.callApi(
        '/sentiment_detectors/{instance_name}/retrieve', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
