/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClassLabelList from '../model/ClassLabelList';
import ClassLabelPair from '../model/ClassLabelPair';
import CreateDetails from '../model/CreateDetails';
import InstanceDetail from '../model/InstanceDetail';
import InstanceDetailList from '../model/InstanceDetailList';
import LabelledTextSampleList from '../model/LabelledTextSampleList';
import ScoredLabelList from '../model/ScoredLabelList';
import TextInput from '../model/TextInput';
import TotalSamples from '../model/TotalSamples';
import TrainDetails from '../model/TrainDetails';

/**
* Text_classifiers service.
* @module api/Text_classifiersApi
* @version 2.0.3
*/
export default class Text_classifiersApi {

    /**
    * Constructs a new Text_classifiersApi. 
    * @alias module:api/Text_classifiersApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Add training samples.
     * Add training samples to named text classifier. Returns the classifier&#39;s updated number of training samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/LabelledTextSampleList} labelledTextSampleList List of labelled text samples.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TotalSamples} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierAddTrainingSamplesWithHttpInfo(instanceName, labelledTextSampleList) {
      let postBody = labelledTextSampleList;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierAddTrainingSamples");
      }

      // verify the required parameter 'labelledTextSampleList' is set
      if (labelledTextSampleList === undefined || labelledTextSampleList === null) {
        throw new Error("Missing the required parameter 'labelledTextSampleList' when calling controllersTextClassifiersControllerTextClassifierAddTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TotalSamples;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/training_samples', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Add training samples.
     * Add training samples to named text classifier. Returns the classifier&#39;s updated number of training samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/LabelledTextSampleList} labelledTextSampleList List of labelled text samples.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TotalSamples}
     */
    controllersTextClassifiersControllerTextClassifierAddTrainingSamples(instanceName, labelledTextSampleList) {
      return this.controllersTextClassifiersControllerTextClassifierAddTrainingSamplesWithHttpInfo(instanceName, labelledTextSampleList)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a text classifier.
     * Create a new text classifier or load one from the store. Returns the details of the new or loaded instance.
     * @param {module:model/CreateDetails} createDetails The details of the instance to create.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetail} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierCreateWithHttpInfo(createDetails) {
      let postBody = createDetails;

      // verify the required parameter 'createDetails' is set
      if (createDetails === undefined || createDetails === null) {
        throw new Error("Missing the required parameter 'createDetails' when calling controllersTextClassifiersControllerTextClassifierCreate");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetail;

      return this.apiClient.callApi(
        '/text_classifiers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create a text classifier.
     * Create a new text classifier or load one from the store. Returns the details of the new or loaded instance.
     * @param {module:model/CreateDetails} createDetails The details of the instance to create.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetail}
     */
    controllersTextClassifiersControllerTextClassifierCreate(createDetails) {
      return this.controllersTextClassifiersControllerTextClassifierCreateWithHttpInfo(createDetails)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Endpoint to aid in the curation of a model instance.
     * Returns the list of samples behind a cell of the confusion matrix of the training or testing samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/ClassLabelPair} labelPair The true label, predicted label and matrix (train/test) to use.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LabelledTextSampleList} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierCurateWithHttpInfo(instanceName, labelPair) {
      let postBody = labelPair;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierCurate");
      }

      // verify the required parameter 'labelPair' is set
      if (labelPair === undefined || labelPair === null) {
        throw new Error("Missing the required parameter 'labelPair' when calling controllersTextClassifiersControllerTextClassifierCurate");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LabelledTextSampleList;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/curate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Endpoint to aid in the curation of a model instance.
     * Returns the list of samples behind a cell of the confusion matrix of the training or testing samples.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/ClassLabelPair} labelPair The true label, predicted label and matrix (train/test) to use.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LabelledTextSampleList}
     */
    controllersTextClassifiersControllerTextClassifierCurate(instanceName, labelPair) {
      return this.controllersTextClassifiersControllerTextClassifierCurateWithHttpInfo(instanceName, labelPair)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete training samples.
     * Delete the training samples of the named text classifier. Returns the deleted samples.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LabelledTextSampleList} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierDelTrainingSamplesWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierDelTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LabelledTextSampleList;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/training_samples', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete training samples.
     * Delete the training samples of the named text classifier. Returns the deleted samples.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LabelledTextSampleList}
     */
    controllersTextClassifiersControllerTextClassifierDelTrainingSamples(instanceName) {
      return this.controllersTextClassifiersControllerTextClassifierDelTrainingSamplesWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get details of named instance.
     * Get the details of the named text classifier instance.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetail} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierGetDetailsWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierGetDetails");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetail;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get details of named instance.
     * Get the details of the named text classifier instance.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetail}
     */
    controllersTextClassifiersControllerTextClassifierGetDetails(instanceName) {
      return this.controllersTextClassifiersControllerTextClassifierGetDetailsWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get list of loaded text classifiers.
     * Get the list of loaded text classifiers.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetailList} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierGetDetailsAllWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetailList;

      return this.apiClient.callApi(
        '/text_classifiers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get list of loaded text classifiers.
     * Get the list of loaded text classifiers.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetailList}
     */
    controllersTextClassifiersControllerTextClassifierGetDetailsAll() {
      return this.controllersTextClassifiersControllerTextClassifierGetDetailsAllWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get list of possible labels.
     * Returns the classifier&#39;s list of possible class labels.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ClassLabelList} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierGetLabelsWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierGetLabels");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ClassLabelList;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/get_labels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get list of possible labels.
     * Returns the classifier&#39;s list of possible class labels.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ClassLabelList}
     */
    controllersTextClassifiersControllerTextClassifierGetLabels(instanceName) {
      return this.controllersTextClassifiersControllerTextClassifierGetLabelsWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get training samples.
     * Get the training samples of the named text classifier.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/LabelledTextSampleList} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierGetTrainingSamplesWithHttpInfo(instanceName) {
      let postBody = null;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierGetTrainingSamples");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = LabelledTextSampleList;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/training_samples', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get training samples.
     * Get the training samples of the named text classifier.
     * @param {String} instanceName The name of the model instance.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/LabelledTextSampleList}
     */
    controllersTextClassifiersControllerTextClassifierGetTrainingSamples(instanceName) {
      return this.controllersTextClassifiersControllerTextClassifierGetTrainingSamplesWithHttpInfo(instanceName)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Classify text.
     * Classifies the text and returns a probability sorted list of classes.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TextInput} textInput The input text.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ScoredLabelList} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierRetrieveWithHttpInfo(instanceName, textInput) {
      let postBody = textInput;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierRetrieve");
      }

      // verify the required parameter 'textInput' is set
      if (textInput === undefined || textInput === null) {
        throw new Error("Missing the required parameter 'textInput' when calling controllersTextClassifiersControllerTextClassifierRetrieve");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ScoredLabelList;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/retrieve', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Classify text.
     * Classifies the text and returns a probability sorted list of classes.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TextInput} textInput The input text.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ScoredLabelList}
     */
    controllersTextClassifiersControllerTextClassifierRetrieve(instanceName, textInput) {
      return this.controllersTextClassifiersControllerTextClassifierRetrieveWithHttpInfo(instanceName, textInput)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Train the named text classifier.
     * Train the named text classifier with the training and testing data already provided. Returns the details of the model instance.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TrainDetails} trainDetails The arguments provided to the train operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceDetail} and HTTP response
     */
    controllersTextClassifiersControllerTextClassifierTrainWithHttpInfo(instanceName, trainDetails) {
      let postBody = trainDetails;

      // verify the required parameter 'instanceName' is set
      if (instanceName === undefined || instanceName === null) {
        throw new Error("Missing the required parameter 'instanceName' when calling controllersTextClassifiersControllerTextClassifierTrain");
      }

      // verify the required parameter 'trainDetails' is set
      if (trainDetails === undefined || trainDetails === null) {
        throw new Error("Missing the required parameter 'trainDetails' when calling controllersTextClassifiersControllerTextClassifierTrain");
      }


      let pathParams = {
        'instance_name': instanceName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKeyHeader'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InstanceDetail;

      return this.apiClient.callApi(
        '/text_classifiers/{instance_name}/train', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Train the named text classifier.
     * Train the named text classifier with the training and testing data already provided. Returns the details of the model instance.
     * @param {String} instanceName The name of the model instance.
     * @param {module:model/TrainDetails} trainDetails The arguments provided to the train operation.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceDetail}
     */
    controllersTextClassifiersControllerTextClassifierTrain(instanceName, trainDetails) {
      return this.controllersTextClassifiersControllerTextClassifierTrainWithHttpInfo(instanceName, trainDetails)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
