/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ClassLabel from './model/ClassLabel';
import ClassLabelList from './model/ClassLabelList';
import ClassLabelPair from './model/ClassLabelPair';
import CreateDetails from './model/CreateDetails';
import DashboardDetail from './model/DashboardDetail';
import DashboardModelDetail from './model/DashboardModelDetail';
import DateList from './model/DateList';
import DucklingEntCreateDetails from './model/DucklingEntCreateDetails';
import DucklingInstanceDetail from './model/DucklingInstanceDetail';
import DucklingInstanceDetailList from './model/DucklingInstanceDetailList';
import Entity from './model/Entity';
import EntityList from './model/EntityList';
import InstanceDetail from './model/InstanceDetail';
import InstanceDetailList from './model/InstanceDetailList';
import LabeledWordManifold from './model/LabeledWordManifold';
import LabelledTextSample from './model/LabelledTextSample';
import LabelledTextSampleList from './model/LabelledTextSampleList';
import Lr4CreateDetails from './model/Lr4CreateDetails';
import Lr4InstanceDetail from './model/Lr4InstanceDetail';
import Lr4InstanceDetailList from './model/Lr4InstanceDetailList';
import ModelDate from './model/ModelDate';
import NewWord from './model/NewWord';
import NewWordList from './model/NewWordList';
import RegexEntCreateDetails from './model/RegexEntCreateDetails';
import RegexInstanceDetail from './model/RegexInstanceDetail';
import RegexInstanceDetailList from './model/RegexInstanceDetailList';
import ScoredLabel from './model/ScoredLabel';
import ScoredLabelList from './model/ScoredLabelList';
import Sentiment from './model/Sentiment';
import SimilarityEntCreateDetails from './model/SimilarityEntCreateDetails';
import SimilarityInstanceDetail from './model/SimilarityInstanceDetail';
import SimilarityInstanceDetailList from './model/SimilarityInstanceDetailList';
import TextInput from './model/TextInput';
import TotalSamples from './model/TotalSamples';
import TrainDetails from './model/TrainDetails';
import WordAndDistance from './model/WordAndDistance';
import WordAndDistanceList from './model/WordAndDistanceList';
import WordAndThreshold from './model/WordAndThreshold';
import DashboardApi from './api/DashboardApi';
import Date_parsersApi from './api/Date_parsersApi';
import Duckling_entity_extractorsApi from './api/Duckling_entity_extractorsApi';
import Faq_matchersApi from './api/Faq_matchersApi';
import Intent_classifiersApi from './api/Intent_classifiersApi';
import Lr4_language_recognisersApi from './api/Lr4_language_recognisersApi';
import Regex_entity_extractorsApi from './api/Regex_entity_extractorsApi';
import Sentiment_detectorsApi from './api/Sentiment_detectorsApi';
import Similarity_entity_extractorsApi from './api/Similarity_entity_extractorsApi';
import Text_classifiersApi from './api/Text_classifiersApi';
import Word_manifoldsApi from './api/Word_manifoldsApi';


/**
* This_is_the_HTTP_API_for_Feersum_NLU__See_httpsgithub_compraekeltfeersum_nlu_api_wrappers_for_examples_of_how_to_use_the_API_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FeersumNluApi = require('index'); // See note below*.
* var xxxSvc = new FeersumNluApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FeersumNluApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FeersumNluApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FeersumNluApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.3
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ClassLabel model constructor.
     * @property {module:model/ClassLabel}
     */
    ClassLabel,

    /**
     * The ClassLabelList model constructor.
     * @property {module:model/ClassLabelList}
     */
    ClassLabelList,

    /**
     * The ClassLabelPair model constructor.
     * @property {module:model/ClassLabelPair}
     */
    ClassLabelPair,

    /**
     * The CreateDetails model constructor.
     * @property {module:model/CreateDetails}
     */
    CreateDetails,

    /**
     * The DashboardDetail model constructor.
     * @property {module:model/DashboardDetail}
     */
    DashboardDetail,

    /**
     * The DashboardModelDetail model constructor.
     * @property {module:model/DashboardModelDetail}
     */
    DashboardModelDetail,

    /**
     * The DateList model constructor.
     * @property {module:model/DateList}
     */
    DateList,

    /**
     * The DucklingEntCreateDetails model constructor.
     * @property {module:model/DucklingEntCreateDetails}
     */
    DucklingEntCreateDetails,

    /**
     * The DucklingInstanceDetail model constructor.
     * @property {module:model/DucklingInstanceDetail}
     */
    DucklingInstanceDetail,

    /**
     * The DucklingInstanceDetailList model constructor.
     * @property {module:model/DucklingInstanceDetailList}
     */
    DucklingInstanceDetailList,

    /**
     * The Entity model constructor.
     * @property {module:model/Entity}
     */
    Entity,

    /**
     * The EntityList model constructor.
     * @property {module:model/EntityList}
     */
    EntityList,

    /**
     * The InstanceDetail model constructor.
     * @property {module:model/InstanceDetail}
     */
    InstanceDetail,

    /**
     * The InstanceDetailList model constructor.
     * @property {module:model/InstanceDetailList}
     */
    InstanceDetailList,

    /**
     * The LabeledWordManifold model constructor.
     * @property {module:model/LabeledWordManifold}
     */
    LabeledWordManifold,

    /**
     * The LabelledTextSample model constructor.
     * @property {module:model/LabelledTextSample}
     */
    LabelledTextSample,

    /**
     * The LabelledTextSampleList model constructor.
     * @property {module:model/LabelledTextSampleList}
     */
    LabelledTextSampleList,

    /**
     * The Lr4CreateDetails model constructor.
     * @property {module:model/Lr4CreateDetails}
     */
    Lr4CreateDetails,

    /**
     * The Lr4InstanceDetail model constructor.
     * @property {module:model/Lr4InstanceDetail}
     */
    Lr4InstanceDetail,

    /**
     * The Lr4InstanceDetailList model constructor.
     * @property {module:model/Lr4InstanceDetailList}
     */
    Lr4InstanceDetailList,

    /**
     * The ModelDate model constructor.
     * @property {module:model/ModelDate}
     */
    ModelDate,

    /**
     * The NewWord model constructor.
     * @property {module:model/NewWord}
     */
    NewWord,

    /**
     * The NewWordList model constructor.
     * @property {module:model/NewWordList}
     */
    NewWordList,

    /**
     * The RegexEntCreateDetails model constructor.
     * @property {module:model/RegexEntCreateDetails}
     */
    RegexEntCreateDetails,

    /**
     * The RegexInstanceDetail model constructor.
     * @property {module:model/RegexInstanceDetail}
     */
    RegexInstanceDetail,

    /**
     * The RegexInstanceDetailList model constructor.
     * @property {module:model/RegexInstanceDetailList}
     */
    RegexInstanceDetailList,

    /**
     * The ScoredLabel model constructor.
     * @property {module:model/ScoredLabel}
     */
    ScoredLabel,

    /**
     * The ScoredLabelList model constructor.
     * @property {module:model/ScoredLabelList}
     */
    ScoredLabelList,

    /**
     * The Sentiment model constructor.
     * @property {module:model/Sentiment}
     */
    Sentiment,

    /**
     * The SimilarityEntCreateDetails model constructor.
     * @property {module:model/SimilarityEntCreateDetails}
     */
    SimilarityEntCreateDetails,

    /**
     * The SimilarityInstanceDetail model constructor.
     * @property {module:model/SimilarityInstanceDetail}
     */
    SimilarityInstanceDetail,

    /**
     * The SimilarityInstanceDetailList model constructor.
     * @property {module:model/SimilarityInstanceDetailList}
     */
    SimilarityInstanceDetailList,

    /**
     * The TextInput model constructor.
     * @property {module:model/TextInput}
     */
    TextInput,

    /**
     * The TotalSamples model constructor.
     * @property {module:model/TotalSamples}
     */
    TotalSamples,

    /**
     * The TrainDetails model constructor.
     * @property {module:model/TrainDetails}
     */
    TrainDetails,

    /**
     * The WordAndDistance model constructor.
     * @property {module:model/WordAndDistance}
     */
    WordAndDistance,

    /**
     * The WordAndDistanceList model constructor.
     * @property {module:model/WordAndDistanceList}
     */
    WordAndDistanceList,

    /**
     * The WordAndThreshold model constructor.
     * @property {module:model/WordAndThreshold}
     */
    WordAndThreshold,

    /**
    * The DashboardApi service constructor.
    * @property {module:api/DashboardApi}
    */
    DashboardApi,

    /**
    * The Date_parsersApi service constructor.
    * @property {module:api/Date_parsersApi}
    */
    Date_parsersApi,

    /**
    * The Duckling_entity_extractorsApi service constructor.
    * @property {module:api/Duckling_entity_extractorsApi}
    */
    Duckling_entity_extractorsApi,

    /**
    * The Faq_matchersApi service constructor.
    * @property {module:api/Faq_matchersApi}
    */
    Faq_matchersApi,

    /**
    * The Intent_classifiersApi service constructor.
    * @property {module:api/Intent_classifiersApi}
    */
    Intent_classifiersApi,

    /**
    * The Lr4_language_recognisersApi service constructor.
    * @property {module:api/Lr4_language_recognisersApi}
    */
    Lr4_language_recognisersApi,

    /**
    * The Regex_entity_extractorsApi service constructor.
    * @property {module:api/Regex_entity_extractorsApi}
    */
    Regex_entity_extractorsApi,

    /**
    * The Sentiment_detectorsApi service constructor.
    * @property {module:api/Sentiment_detectorsApi}
    */
    Sentiment_detectorsApi,

    /**
    * The Similarity_entity_extractorsApi service constructor.
    * @property {module:api/Similarity_entity_extractorsApi}
    */
    Similarity_entity_extractorsApi,

    /**
    * The Text_classifiersApi service constructor.
    * @property {module:api/Text_classifiersApi}
    */
    Text_classifiersApi,

    /**
    * The Word_manifoldsApi service constructor.
    * @property {module:api/Word_manifoldsApi}
    */
    Word_manifoldsApi
};
