/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FeersumNluApi);
  }
}(this, function(expect, FeersumNluApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FeersumNluApi.Duckling_entity_extractorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Duckling_entity_extractorsApi', function() {
    describe('controllersDucklingEntityExtractorsControllerDucklingEntityExtractorCreate', function() {
      it('should call controllersDucklingEntityExtractorsControllerDucklingEntityExtractorCreate successfully', function(done) {
        //uncomment below and update the code to test controllersDucklingEntityExtractorsControllerDucklingEntityExtractorCreate
        //instance.controllersDucklingEntityExtractorsControllerDucklingEntityExtractorCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetails', function() {
      it('should call controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetails successfully', function(done) {
        //uncomment below and update the code to test controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetails
        //instance.controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetailsAll', function() {
      it('should call controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetailsAll successfully', function(done) {
        //uncomment below and update the code to test controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetailsAll
        //instance.controllersDucklingEntityExtractorsControllerDucklingEntityExtractorGetDetailsAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('controllersDucklingEntityExtractorsControllerDucklingEntityExtractorRetrieve', function() {
      it('should call controllersDucklingEntityExtractorsControllerDucklingEntityExtractorRetrieve successfully', function(done) {
        //uncomment below and update the code to test controllersDucklingEntityExtractorsControllerDucklingEntityExtractorRetrieve
        //instance.controllersDucklingEntityExtractorsControllerDucklingEntityExtractorRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
