/**
 * FeersumNLU API
 * This is the HTTP API for Feersum NLU. See https://github.com/praekelt/feersum-nlu-api-wrappers for examples of how to use the API.
 *
 * OpenAPI spec version: 2.0.3
 * Contact: nlu@feersum.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FeersumNluApi);
  }
}(this, function(expect, FeersumNluApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FeersumNluApi.Intent_classifiersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Intent_classifiersApi', function() {
    describe('intentClassifierAddTrainingSamples', function() {
      it('should call intentClassifierAddTrainingSamples successfully', function(done) {
        //uncomment below and update the code to test intentClassifierAddTrainingSamples
        //instance.intentClassifierAddTrainingSamples(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierCreate', function() {
      it('should call intentClassifierCreate successfully', function(done) {
        //uncomment below and update the code to test intentClassifierCreate
        //instance.intentClassifierCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierCurate', function() {
      it('should call intentClassifierCurate successfully', function(done) {
        //uncomment below and update the code to test intentClassifierCurate
        //instance.intentClassifierCurate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierDelTrainingSamples', function() {
      it('should call intentClassifierDelTrainingSamples successfully', function(done) {
        //uncomment below and update the code to test intentClassifierDelTrainingSamples
        //instance.intentClassifierDelTrainingSamples(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierGetDetails', function() {
      it('should call intentClassifierGetDetails successfully', function(done) {
        //uncomment below and update the code to test intentClassifierGetDetails
        //instance.intentClassifierGetDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierGetDetailsAll', function() {
      it('should call intentClassifierGetDetailsAll successfully', function(done) {
        //uncomment below and update the code to test intentClassifierGetDetailsAll
        //instance.intentClassifierGetDetailsAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierGetLabels', function() {
      it('should call intentClassifierGetLabels successfully', function(done) {
        //uncomment below and update the code to test intentClassifierGetLabels
        //instance.intentClassifierGetLabels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierGetTrainingSamples', function() {
      it('should call intentClassifierGetTrainingSamples successfully', function(done) {
        //uncomment below and update the code to test intentClassifierGetTrainingSamples
        //instance.intentClassifierGetTrainingSamples(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierOnlineTrainingSamples', function() {
      it('should call intentClassifierOnlineTrainingSamples successfully', function(done) {
        //uncomment below and update the code to test intentClassifierOnlineTrainingSamples
        //instance.intentClassifierOnlineTrainingSamples(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierRetrieve', function() {
      it('should call intentClassifierRetrieve successfully', function(done) {
        //uncomment below and update the code to test intentClassifierRetrieve
        //instance.intentClassifierRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('intentClassifierTrain', function() {
      it('should call intentClassifierTrain successfully', function(done) {
        //uncomment below and update the code to test intentClassifierTrain
        //instance.intentClassifierTrain(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
